name: pyjamas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.3
  - snakemake-minimal=5.8.1
  - rise
  - pandas=0.25.3
  - pip
  - sourmash=2.3.0
  - pip:
    - jupyter-contrib-nbextensions
